### ISSUE TITLE
Add badges to the README

### ISSUE THREAD

**Issue by chasinglogic** [chasinglogic/taskforge#54]
Travis, docs, license, and pypi badges would be awesome.

**Comment by zackse** [comment]
Apologies for the noise -- I was repeatedly pushing to my fork to test out the images. See PR #73 for the most recent version.

Note that we should be able to pull the license data from PyPI, but it seems to be inaccurate -- see [https://img.shields.io/pypi/l/taskforge-cli.svg](https://img.shields.io/pypi/l/taskforge-cli.svg).

Also, I couldn't find this project on readthedocs, but that site also offers a badge "API" (e.g., `https://readthedocs.org/projects/taskforge-cli/badge/`).

Hope this helps!

**Comment by chasinglogic** [comment]
No problem for the noise, I only get a notification for comments not commits.

Thanks for knocking this out!
