### ISSUE TITLE
Write docs for `task todo` command   

### ISSUE THREAD

**Issue by chasinglogic** [chasinglogic/taskforge#6]

**Comment by maurobaraldi** [comment]
Hey, I would like to help with this issues. How's the best way to start?

**Comment by chasinglogic** [comment]
Hey @maurobaraldi 

You'll just need to create a restructured text document in `src/docs/cli/` named `task_todo.rst`. As for content you can see `task_add.rst` as an example.

Feel free to add any further explanation you think would enhance that particular document.

**Comment by maurobaraldi** [comment]
Done :-) #28
