### ISSUE TITLE
Write bot / script that crawls all links on the documenation website and finds any 404s

### ISSUE THREAD

**Issue by chasinglogic** [chasinglogic/taskforge#65]
could be a script in `scripts/` or a docker container we run that continuously checks. Ideally if it was a script we could plug it into the CI system somehow.

**Comment by GoelBiju** [comment]
Hi @chasinglogic,

Is this script to crawl all links located at http://taskforge.io/docs/?

**Comment by chasinglogic** [comment]
Can we integrate this with Travis-CI during the documentation linting before we deploy the website?

i.e. We could build the docker container and run it locally I imagine during the build and run this tool against it there.

**Comment by chasinglogic** [comment]
It looks like a script like this would work to me:

```
make website
docker run -p 8080:80 -d chasinglogic/taskforge.io:latest
pylinkvalidator.py -P https://localhost:8080
```

Assuming you had pylinkvalidator installed. @GoelBiju would you like to submit a PR for this in Travis? You did all the hard work on this one.
